GET http://127.0.0.1:3002/api/getAllEvents
Content-Type: application/json

###
POST http://localhost:3002/api/createEvent
Content-Type: application/json

{ 
      
    "name": "Marry Crismiss",
    "venue":"Lahore",
    "date": "2020-12-23T05:46:01.776Z"
}

###
GET http://localhost:3002/api/getEvent/1

###

PUT http://localhost:3002/api/updateEvent/1
Content-Type: application/json

{
    "name": "Quaid Day",
    "venue":"Lahore, Punjab Pakistan",
    "date": "2020-12-23T05:46:01.776Z"
}
###
DELETE http://localhost:3002/api/deleteEvent/1
